# Generated by Django 3.2.10 on 2023-08-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploaded_pdfs/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
