# Generated by Django 3.2.10 on 2023-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraturePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(help_text='Comma-separated list of authors')),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
